preset: none

enabled:
  - blank_line_after_namespace
  - braces
  - class_definition
  - elseif
  - encoding
  - full_opening_tag
  - function_declaration
  - lowercase_constants
  - lowercase_keywords
  - method_argument_space
  - no_closing_tag
  - no_spaces_after_function_name
  - no_spaces_inside_parenthesis
  - no_tab_indentation
  - no_trailing_whitespace
  - no_trailing_whitespace_in_comment
  - psr4
  - single_blank_line_at_eof
  - single_class_element_per_statement
  - single_import_per_statement
  - single_line_after_imports
  - switch_case_semicolon_to_colon
  - switch_case_space
  - unix_line_endings
  - method_visibility_required
  - blank_line_before_return
  - cast_spaces
  - concat_with_spaces
  - declare_equal_normalize
  - declare_strict_types
  - function_typehint_space
  - hash_to_slash_comment
  - linebreak_after_opening_tag
  - lowercase_cast
  - method_separation
  - modernize_types_casting
  - native_function_casing
  - new_with_braces
  - no_blank_lines_after_class_opening
  - no_blank_lines_after_phpdoc
  - no_empty_comment
  - no_empty_phpdoc
  - no_empty_statement
  - no_extra_consecutive_blank_lines
  - no_leading_import_slash
  - no_leading_namespace_whitespace
  - no_multiline_whitespace_around_double_arrow
  - no_multiline_whitespace_before_semicolons
  - no_php4_constructor
  - no_short_bool_cast
  - no_short_echo_tag
  - no_singleline_whitespace_before_semicolons
  - no_spaces_inside_offset
  - no_trailing_comma_in_list_call
  - no_trailing_comma_in_singleline_array
  - no_unused_imports
  - no_useless_else
  - no_useless_return
  - no_whitespace_before_comma_in_array
  - no_whitespace_in_blank_line
  - normalize_index_brace
  - alpha_ordered_imports
  - phpdoc_align
  - phpdoc_annotation_without_dot
  - phpdoc_indent
  - phpdoc_scalar
  - phpdoc_single_line_var_spacing
  - random_api_migration
  - self_accessor
  - semicolon_after_instruction
  - short_array_syntax
  - short_scalar_cast
  - single_blank_line_before_namespace
  - single_quote
  - standardize_not_equals
  - strict_comparison
  - ternary_operator_spaces
  - trailing_comma_in_multiline_array
  - trim_array_spaces
  - unalign_double_arrow
  - unalign_equals
  - unary_operator_spaces
  - whitespace_after_comma_in_array
  - no_blank_lines_after_return
  - no_blank_lines_after_throw
  - no_blank_lines_between_imports
  - no_blank_lines_between_traits
  - no_extra_block_blank_lines
  - no_spaces_outside_offset
  - property_visibility_required
  - return_type_declaration
